version: "3.9"

services:
  puppint:
    build: .
    container_name: puppint_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./api.env
    working_dir: /app
    command: >
      sh -c "python puppint.py"